# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeBinaryMultiEntropyConditional <- function(appr, non_informative_threshold = 0L) {
    .Call(`_RandomForestDist_computeBinaryMultiEntropyConditional`, appr, non_informative_threshold)
}

computeBinaryMultiEntropyFrequencies <- function(appr) {
    .Call(`_RandomForestDist_computeBinaryMultiEntropyFrequencies`, appr)
}

estimateBernoulliGammabc3 <- function(y, non_informative_beta) {
    .Call(`_RandomForestDist_estimateBernoulliGammabc3`, y, non_informative_beta)
}

estimateGammaBC3 <- function(y, non_informative_beta) {
    .Call(`_RandomForestDist_estimateGammaBC3`, y, non_informative_beta)
}

simulateDist <- function(n, prediction, distribution) {
    .Call(`_RandomForestDist_simulateDist`, n, prediction, distribution)
}

