# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimateGammaBC3 <- function(y) {
    .Call(`_RandomForest2_estimateGammaBC3`, y)
}

simulateDist <- function(n, prediction, distribution) {
    .Call(`_RandomForest2_simulateDist`, n, prediction, distribution)
}

